### ISSUE TITLE
[Question]: I am Unable to Sort if it is Done & How to Add Filter Form in Header

### ISSUE THREAD

**Issue by abbasmashaddy72** [mokhosh/filament-kanban#11]
### What happened?

I would like to add this type of Form, using Schema How can achieve it?

![image](https://github.com/mokhosh/filament-kanban/assets/55267488/0994dba0-a053-497e-9124-61f095afc5b5)

Sometime having issue Unable to if it is done: as you see in the first Part of Video

https://github.com/mokhosh/filament-kanban/assets/55267488/d82ee0d5-c184-4553-9ed0-8ed6cc5b76be

### How to reproduce the bug

None

### Package Version

2.2

### PHP Version

8.2

### Laravel Version

10.10

**Comment by mokhosh** [comment]
Filtering: we don't have this in the package. So you will need to create a form in your `kanban-view`, and then use the data from that form to filter your records in the `records` method.

The "Done" issue: maybe you can check the dev tools, and see if there are any errors, or create a replication repository so I can check the issue.

**Comment by abbasmashaddy72** [comment]
getHeaderActions are not rendering, but When I do dd inside the function it is working but not rendering:

is there anything that I am missing


```php
protected function getHeaderActions(): array
{
    return [
        Actions\Action::make('manage-sprints')
            ->button()
            ->visible(fn () => $this->project->currentSprint)
            ->label(__('Manage sprints'))
            ->color('primary')
            ->url(route('filament.admin.resources.projects.edit', ['record' => $this->project, 'tenant' => \Filament\Facades\Filament::getTenant()->id])),

        Actions\Action::make('refresh')
            ->button()
            ->visible(fn () => $this->project->currentSprint)
            ->label(__('Refresh'))
            ->color('secondary')
            ->action(function () {
                $this->getRecords();
                Notification::make()
                    ->title(__('Kanban board updated'))
                    ->success()
                    ->send();
            }),
    ];
}
```

**Comment by mokhosh** [comment]
I copy pasted your code into a project of mine and it works fine.
Check these two things:
- Make sure you're importing the right `Action` class. It should be `Filament\Actions\Action`.
- Check if `$this->project->currentSprint` is returning true. Because you're hiding it yourself if it's `false` with `visible()`
