### ISSUE TITLE
[Bug]: Cant use on fresh laravel 11

### ISSUE THREAD

**Issue by djoey123** [mokhosh/filament-kanban#28]
### What happened?

I can't get it working right.

Installed package.
Run: php artisan filament-kanban:install
Doesn't seem like it published any files.

Followed the example.
I see there is an app/Providers/Filament/AdminPanelProvider for example.
copied in my own project. Doesn't seems to do anything

Registered the Provider in: /bootstrap/providers.php
Seems to work.
Go to /admin/login no css/js loaded.

I think the package does not work well with the new structure of Laravel

### How to reproduce the bug

Fresh install laravel 11

### Package Version

2.7.0

### PHP Version

8.3.2

### Laravel Version

11.1.1

### Which operating systems does with happen with?

Windows

**Comment by mokhosh** [comment]
The package works fine with laravel 11.

looking at your explanations, doesn't seem like you've worked with it on laravel 10.

please follow the read me, or watch the videos to see how to get started with the plugin.

**Comment by djoey123** [comment]
Sorry...
I missed totally that it is an plugin for filament.
i come from: https://laravel-news.com/filament-kanban

And the only mentioning is: Easily add Kanban board pages to your Filament panels.

Sorry for bothering you
