### ISSUE TITLE
[Bug]: Cannot view multiple boards on smallest breakpoint either via vertical or horizontal scrolling

### ISSUE THREAD

**Issue by ryanmortier** [mokhosh/filament-kanban#30]
### What happened?

On the smallest breakpoint, you cannot see any boards past the first whether you scroll vertically or horizonally.

Here is a gif:

![CleanShot 2024-04-05 at 14 39 52](https://github.com/mokhosh/filament-kanban/assets/2053960/fc1323a8-9ca7-497f-9224-6cb8a55468ec)

### How to reproduce the bug

Try scrolling to other boards when on the smallest breakpoint.

### Package Version

2

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS

### Which browsers does with happen with?

Chrome

**Comment by mokhosh** [comment]
Are you sure you have the latest version?
Have you published the views? If so, are your views in sync with the latest changes?

This is what I have:


https://github.com/mokhosh/filament-kanban/assets/6499685/933a2101-a6e8-46c1-bd8e-30395b233ed3

**Comment by ryanmortier** [comment]
I just cloned this repo to test: https://github.com/mokhosh/filament-kanban-todo

I'll check on Monday if it exists with updates.

**Comment by ryanmortier** [comment]
I did a `composer update` on the demo repo. I do not have views published. One example works but the other doesn't so perhaps I should just close this issue and try to implement in my own project before reopening? Here is another gif:

![CleanShot 2024-04-08 at 08 48 54](https://github.com/mokhosh/filament-kanban/assets/2053960/d5cdbcb6-67b5-40c9-94a6-72a8558ab52e)

**Comment by mokhosh** [comment]
@ryanmortier, yes, the one that doesn't work clearly has a customized view. I'll have to update the demo views with the latest changes. thanks.
