### ISSUE TITLE
[Bug]: Vertical scrollbar issue

### ISSUE THREAD

**Issue by zanstro** [mokhosh/filament-kanban#52]
### What happened?

After I upgraded from version 2.0.0 to version 2.8.0 a vertical scrollbar appears in the kanban widget as shown in the screenshot.
![Screenshot 2024-08-19 at 1 28 17 PM](https://github.com/user-attachments/assets/eccd3745-f5cf-4b2c-99da-0c37cddbf229)

### How to reproduce the bug

Upgrade to 2.8.0

### Package Version

2.8.0

### PHP Version

8.2

### Laravel Version

11.20.0

**Comment by mokhosh** [comment]
I don't have this.
Which operating system and browser are you using?

**Comment by tarikaydin16** [comment]
<img width="1888" alt="image" src="https://github.com/user-attachments/assets/6a9c0232-64bd-4418-96fc-b802c37c70fc">
I have same problem. I try downgrading to 2.7.0 but doesnt work.
My OS is macos and My browser Opera, Google chorme.

**Comment by mokhosh** [comment]
I still can't reproduce this. I'm also on macos, and I've tried chrome and arc.

Feel free to find the issue and open a PR for this.

**Comment by joaocorrea-dicorpo** [comment]
I have the same issue, and I solved it by changing the kanban-board.blade.php a little bit, keeping it like this:
```
<x-filament-panels::page>    
    <div class="h-full flex flex-col">
        <div class="flex-1 overflow-auto">
            <div 
                x-data 
                wire:ignore.self 
                class="md:flex gap-4 min-h-full"
            >
                @foreach($statuses as $status)
                    @include(static::$statusView)
                @endforeach

                <div wire:ignore>
                    @include(static::$scriptsView)
                </div>
            </div>

        </div>

    </div>

    @unless($disableEditModal)
        <x-filament-kanban::edit-record-modal/>
    @endunless

</x-filament-panels::page> 
```
...
It seems like there's some kind of conflict between overflow-x-auto and overflow-y-hidden. I tested it on Chrome and Firefox, and both had the same problem.
